# Generated by Django 5.1.4 on 2024-12-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='diets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='ready_in_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='servings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
